Repository barrycumbie/animated-octo-adventure, pull requests merged in 2022-02, with the labels that each got.

#150 Iss137
  src/app/app.component.html
Labels: task

#152 profile
  dev-team/samantha.html
Labels: task

#153 added footer component
  index.html
  src/app/app.component.html
  src/app/app.module.ts
  src/app/footer/footer.component.css
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
Labels: story

#160 added meme component
  package-lock.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/meme/meme.component.css
  src/app/meme/meme.component.html
  src/app/meme/meme.component.spec.ts
  src/app/meme/meme.component.ts
Labels: task

#169 Iss168
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/services/weatherdata.service.spec.ts
  src/app/services/weatherdata.service.ts
  src/app/weather/weather.component.html
  src/app/weather/weather.component.ts
  tsconfig.json
Labels: task

#170 Revert "Iss168"
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/services/weatherdata.service.spec.ts
  src/app/services/weatherdata.service.ts
  src/app/weather/weather.component.html
  src/app/weather/weather.component.ts
  tsconfig.json
Labels: task

#167 added new feature to schedule component
  src/app/component-schedule/component-schedule.component.html
Labels: task

#164 adding weather snippet to weather component
  src/app/weather/weather.component.css
  src/app/weather/weather.component.html
Labels: task

#172 adds a button to tag component
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/tag-component/tag-component.component.html
Labels: epic

#175 Iss174
  src/app/weather/degree/degree.component.css
  src/app/weather/degree/degree.component.html
  src/app/weather/degree/degree.component.spec.ts
  src/app/weather/degree/degree.component.ts
Labels: task
